apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
      namespace: kube-system
  chart:
    spec:
      chart: karpenter
      version: "1.8.2"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
      interval: 12h
  values:
    replicas: 1
    dnsPolicy: Default

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${KARPENTER_ROLE_ARN}

    settings:
      clusterName: ${CLUSTER_NAME}
      clusterEndpoint: ${CLUSTER_ENDPOINT}
      interruptionQueue: ${KARPENTER_QUEUE_NAME}

    webhook:
      enabled: false

    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
