replicaCount: 1

image:
  repository: ghcr.io/ldsouza1220/csv-uploader/csv-uploader
  tag: "18bb2f5"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

env:
  - name: ENVIRONMENT
    value: local
  - name: DATABASE_URL
    value: "sqlite:////data/csv_processor.db"
  - name: S3_ENDPOINT_URL
    value: "http://minio.dev.svc.cluster.local:9000"
  - name: S3_BUCKET_NAME
    value: csv-files
  - name: AWS_ACCESS_KEY_ID
    value: minioadmin
  - name: AWS_SECRET_ACCESS_KEY
    value: minioadmin123

persistence:
  enabled: false

autoscaling:
  enabled: false

httpRoute:
  enabled: false

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: csv.local
      paths:
        - path: /
          pathType: Prefix
