apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panda-secret.fullname" . }}
  labels:
    {{- include "panda-secret.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret.json: |
    {"secret": {{ .Values.secret.pandaSecret | quote }}}
